In [1]:
import pandas as pd

In [ ]:
ANSWERS_CSV_URL = "https://raw.githubusercontent.com/dawtasso/eu_survey_correlation/refs/heads/main/data/surveys/volume_b_answer_distributions.csv"

In [3]:
df = pd.read_csv(ANSWERS_CSV_URL)

In [4]:
df

,sheet_id,file_name,question_clean,answer_label,is_summary,demographic_type,demographic_value,count,pct,total_base
0,QA1_2,Fairness_perception_green_transition_2022_ebs_...,Do you agree or disagree that the green transi...,Tout à fait d'accord,False,total,eu27,13232.0,50.0,26395.0
1,QA1_2,Fairness_perception_green_transition_2022_ebs_...,Do you agree or disagree that the green transi...,Tout à fait d'accord,False,gender,male,6198.0,49.0,12635.0
2,QA1_2,Fairness_perception_green_transition_2022_ebs_...,Do you agree or disagree that the green transi...,Tout à fait d'accord,False,gender,female,7018.0,51.0,13739.0
3,QA1_2,Fairness_perception_green_transition_2022_ebs_...,Do you agree or disagree that the green transi...,Tout à fait d'accord,False,income_difficulty,poor,1029.0,49.0,2104.0
4,QA1_2,Fairness_perception_green_transition_2022_ebs_...,Do you agree or disagree that the green transi...,Tout à fait d'accord,False,income_difficulty,medium,3029.0,44.0,6959.0
...,...,...,...,...,...,...,...,...,...,...
16455,Q6_7,fl_506_volume_B.xlsx,Do you agree or disagree that EU Member States...,Total 'Disagree',True,gender,female,1108.0,8.2,13442.0
16456,Q6_7,fl_506_volume_B.xlsx,Do you agree or disagree that EU Member States...,Total 'Disagree',True,occupation,self_employed,270.0,12.5,2163.0
16457,Q6_7,fl_506_volume_B.xlsx,Do you agree or disagree that EU Member States...,Total 'Disagree',True,occupation,employee,1060.0,10.6,10016.0
16458,Q6_7,fl_506_volume_B.xlsx,Do you agree or disagree that EU Member States...,Total 'Disagree',True,occupation,manual_worker,174.0,13.3,1314.0
16459,Q6_7,fl_506_volume_B.xlsx,Do you agree or disagree that EU Member States...,Total 'Disagree',True,occupation,not_working,912.0,7.6,12049.0

In [ ]:
sub_df = df[
    df["question_clean"]
    == "What are the main objectives, in your opinion, for the EU's agriculture and rural development policy? (Multiple answers possible)"
]

In [7]:
sub_df.answer_label.unique()

array(['Assurer un niveau de vie correct aux agriculteurs',
       'Créer de la croissance et des emplois dans les zones rurales',
       'Garantir des prix raisonnables de nourriture pour les consommateurs',
       'Garantir un approvisionnement alimentaire stable dans l’UE de manière constante',
       'Assurer une façon durable de produire des aliments',
       "Protéger l'environnement et lutter contre le changement climatique",
       'Fournir de la nourriture durable, sûre, saine et de grande qualité',
       'Autre (SPONTANÉ)', 'Ne sait pas',
       'Ensuring a fair standard of living for farmers',
       'Creating growth and jobs in rural areas',
       'Ensuring reasonable food prices for consumers',
       'Securing a stable supply of food in the EU',
       'Ensuring a sustainable way to produce food',
       'Protecting the environment and tackling climate change',
       'Providing safe, healthy food of high quality', 'Other (M)',
       "Don't know"], dtype=object)

In [8]:
sub_df

,sheet_id,file_name,question_clean,answer_label,is_summary,demographic_type,demographic_value,count,pct,total_base
4460,QA4,Lien_vers_CAP_2022_eb_sp_520_volume_B.xlsx,"What are the main objectives, in your opinion,...",Assurer un niveau de vie correct aux agriculteurs,False,total,eu27,14398.0,54.0,26511.0
4461,QA4,Lien_vers_CAP_2022_eb_sp_520_volume_B.xlsx,"What are the main objectives, in your opinion,...",Assurer un niveau de vie correct aux agriculteurs,False,gender,male,6767.0,53.0,12680.0
4462,QA4,Lien_vers_CAP_2022_eb_sp_520_volume_B.xlsx,"What are the main objectives, in your opinion,...",Assurer un niveau de vie correct aux agriculteurs,False,gender,female,7627.0,55.0,13813.0
4463,QA4,Lien_vers_CAP_2022_eb_sp_520_volume_B.xlsx,"What are the main objectives, in your opinion,...",Assurer un niveau de vie correct aux agriculteurs,False,occupation,self_employed,968.0,54.0,1779.0
4464,QA4,Lien_vers_CAP_2022_eb_sp_520_volume_B.xlsx,"What are the main objectives, in your opinion,...",Assurer un niveau de vie correct aux agriculteurs,False,occupation,manager,1627.0,53.0,3052.0
...,...,...,...,...,...,...,...,...,...,...
13745,T6,ebs_504_volume_B.xlsx,"What are the main objectives, in your opinion,...",Don't know,False,class_belonging,working_class,70.0,1.0,6058.0
13746,T6,ebs_504_volume_B.xlsx,"What are the main objectives, in your opinion,...",Don't know,False,class_belonging,lower_middle,26.0,1.0,4370.0
13747,T6,ebs_504_volume_B.xlsx,"What are the main objectives, in your opinion,...",Don't know,False,class_belonging,middle,89.0,1.0,13862.0
13748,T6,ebs_504_volume_B.xlsx,"What are the main objectives, in your opinion,...",Don't know,False,class_belonging,upper_middle,4.0,NaN,2342.0
13749,T6,ebs_504_volume_B.xlsx,"What are the main objectives, in your opinion,...",Don't know,False,class_belonging,upper_middle,NaN,NaN,236.0

In [10]:
GITHUB_CSV_URL = "https://raw.githubusercontent.com/dawtasso/eu_survey_correlation/refs/heads/main/data/matches/simplified_michlou_survey_vote_matches_clean.csv"

In [11]:
match_df = pd.read_csv(GITHUB_CSV_URL)

In [ ]:
match_df[
    match_df["question_clean"]
    == "What are the main objectives, in your opinion, for the EU's agriculture and rural development policy? (Multiple answers possible)"
]

,sheet_id,question_clean,question_en,file_name,survey_date,vote_id,summary,summary_clean,vote_date,similarity_score,time_delta
19,T6,"What are the main objectives, in your opinion,...","QA4 In your opinion, which of the following sh...",ebs_504_volume_B.xlsx,2020-11-27,176981,The European Parliament adopted by 622 votes t...,The European Parliament passed a resolution to...,2025-06-17 12:48:00,0.617583,1663
24,T6,"What are the main objectives, in your opinion,...","QA4 In your opinion, which of the following sh...",ebs_504_volume_B.xlsx,2020-11-27,155937,The EU must become food self-sufficient\nInves...,The European Parliament voted to prioritize fo...,2023-06-14 12:46:00,0.610036,929
26,T6,"What are the main objectives, in your opinion,...","QA4 In your opinion, which of the following sh...",ebs_504_volume_B.xlsx,2020-11-27,137235,New policy strengthens biodiversity and adhere...,The European Parliament passed a policy aimed ...,2021-11-23 14:20:00,0.606471,361
68,T6,"What are the main objectives, in your opinion,...","QA4 In your opinion, which of the following sh...",ebs_504_volume_B.xlsx,2020-11-27,178500,"Larger, standalone budget for the common agric...",The European Parliament approved a self-contai...,2025-09-10 13:29:00,0.568526,1748